name = "hhc-calendar-sync"
   main = "worker.js"
   compatibility_date = "2026-07-04"

   [[kv_namespaces]]
   binding = "HHC_KV"
   id = "2130ee8869714250801339b817c4bc16"

   [triggers]
   crons = ["*/15 * * * *"]
